spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


user:
  service:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/eshop_user_service_db
    username: root
    password: Seyfe@1abel
